### ISSUE TITLE
Fix failing GitHub actions.

### ISSUE THREAD

**Issue by nichtich** [gbv/Catmandu-PICA#74] opened 2021-11-30 12:16 UTC
See https://github.com/gbv/Catmandu-PICA/runs/4364199276 - likely requires to fix https://github.com/LibreCat/Catmandu/issues/385.

**Comment by jorol** [comment] 2021-11-30 18:07
The problem is https://github.com/perl4lib/marc-perl/issues/14. I've already created a PR https://github.com/perl4lib/marc-perl/pull/13, but still not merged...

**Closed** 2022-09-19 08:42 UTC
